title: AIT Lab
email: your-email@domain.com
google_analytics: UA-27751621-1

# social links
twitter_username: "ait_eth"
#github_username:  jekyll
#rss: rss
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jekyll
# linkedin_username: jekyll
# pinterest_username: jekyll
# youtube_username: jekyll
# googleplus_username: +jekyll

# Mastodon instances
# mastodon:
# - username: jekyll
#   instance: example.com
# - username: jekyll2
#   instance: example.com

url: https://ait.ethz.ch

show_excerpts: false # set to true to show excerpts on the homepage
future: true

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%b %-d, %Y"


collections:
  news:
    output: false
  publications:
    output: true
    permalink: /:name
  people:
    output: true
    permalink: /:collection/:name
  teaching:
    output: true
    permalink: /:collection/courses/:name

defaults:
  -
    scope:
      path: ""
      type: publications
    values:
      layout: publication
  -
    scope:
      path: ""
      type: people
    values:
      layout: person

  -
    scope:
      path: ""
      type: teaching
    values:
      layout: course

  -
    scope:
      path: ""
      type: workshops
    values:
      layout: event



jekyll_get_json:
  - data: thesis_avail
    json: 'https://feeds.sirop.org/16/09/1609bbd1-fa78-45fc-93e5-ab1d9449b621/1609bbd1-fa78-45fc-93e5-ab1d9449b621.json'
  - data: thesis_taken
    json: 'https://feeds.sirop.org/6f/96/6f9625bc-7d89-4864-ba59-2d8ffea80493/6f9625bc-7d89-4864-ba59-2d8ffea80493.json'



# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.md

# Build settings
theme: minima

plugins:
 - jekyll-seo-tag
 - jekyll-get-json